/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{html,js,svelte,ts}',
  ],
  theme: {
    extend: {
      colors: {
        // Map Tailwind utilities to Figma CSS variables
        // Text colors
        'figma-text': {
          DEFAULT: 'var(--figma-color-text)',
          'secondary': 'var(--figma-color-text-secondary)',
          'tertiary': 'var(--figma-color-text-tertiary)',
          'brand': 'var(--figma-color-text-brand)',
          'component': 'var(--figma-color-text-component)',
          'danger': 'var(--figma-color-text-danger)',
          'success': 'var(--figma-color-text-success)',
          'warning': 'var(--figma-color-text-warning)',
          'disabled': 'var(--figma-color-text-disabled)',
          'onbrand': 'var(--figma-color-text-onbrand)',
          'oncomponent': 'var(--figma-color-text-oncomponent)',
          'ondanger': 'var(--figma-color-text-ondanger)',
          'onsuccess': 'var(--figma-color-text-onsuccess)',
          'onwarning': 'var(--figma-color-text-onwarning)',
          'ondisabled': 'var(--figma-color-text-ondisabled)',
          'onselected': 'var(--figma-color-text-onselected)',
          'oninverse': 'var(--figma-color-text-oninverse)',
          'selected': 'var(--figma-color-text-selected)',
        },
        
        // Background colors
        'figma-bg': {
          DEFAULT: 'var(--figma-color-bg)',
          'secondary': 'var(--figma-color-bg-secondary)',
          'tertiary': 'var(--figma-color-bg-tertiary)',
          'hover': 'var(--figma-color-bg-hover)',
          'pressed': 'var(--figma-color-bg-pressed)',
          'inverse': 'var(--figma-color-bg-inverse)',
          'brand': 'var(--figma-color-bg-brand)',
          'brand-hover': 'var(--figma-color-bg-brand-hover)',
          'brand-pressed': 'var(--figma-color-bg-brand-pressed)',
          'brand-secondary': 'var(--figma-color-bg-brand-secondary)',
          'brand-tertiary': 'var(--figma-color-bg-brand-tertiary)',
          'component': 'var(--figma-color-bg-component)',
          'component-hover': 'var(--figma-color-bg-component-hover)',
          'component-pressed': 'var(--figma-color-bg-component-pressed)',
          'component-secondary': 'var(--figma-color-bg-component-secondary)',
          'component-tertiary': 'var(--figma-color-bg-component-tertiary)',
          'danger': 'var(--figma-color-bg-danger)',
          'danger-hover': 'var(--figma-color-bg-danger-hover)',
          'danger-pressed': 'var(--figma-color-bg-danger-pressed)',
          'danger-secondary': 'var(--figma-color-bg-danger-secondary)',
          'danger-tertiary': 'var(--figma-color-bg-danger-tertiary)',
          'success': 'var(--figma-color-bg-success)',
          'success-hover': 'var(--figma-color-bg-success-hover)',
          'success-pressed': 'var(--figma-color-bg-success-pressed)',
          'success-secondary': 'var(--figma-color-bg-success-secondary)',
          'success-tertiary': 'var(--figma-color-bg-success-tertiary)',
          'warning': 'var(--figma-color-bg-warning)',
          'warning-hover': 'var(--figma-color-bg-warning-hover)',
          'warning-pressed': 'var(--figma-color-bg-warning-pressed)',
          'warning-secondary': 'var(--figma-color-bg-warning-secondary)',
          'warning-tertiary': 'var(--figma-color-bg-warning-tertiary)',
          'disabled': 'var(--figma-color-bg-disabled)',
          'disabled-secondary': 'var(--figma-color-bg-disabled-secondary)',
          'selected': 'var(--figma-color-bg-selected)',
          'selected-hover': 'var(--figma-color-bg-selected-hover)',
          'selected-pressed': 'var(--figma-color-bg-selected-pressed)',
          'selected-secondary': 'var(--figma-color-bg-selected-secondary)',
          'selected-tertiary': 'var(--figma-color-bg-selected-tertiary)',
          'selected-strong': 'var(--figma-color-bg-selected-strong)',
          'onselected': 'var(--figma-color-bg-onselected)',
          'onselected-hover': 'var(--figma-color-bg-onselected-hover)',
          'onselected-pressed': 'var(--figma-color-bg-onselected-pressed)',
        },
        
        // Border colors
        'figma-border': {
          DEFAULT: 'var(--figma-color-border)',
          'strong': 'var(--figma-color-border-strong)',
          'brand': 'var(--figma-color-border-brand)',
          'brand-strong': 'var(--figma-color-border-brand-strong)',
          'component': 'var(--figma-color-border-component)',
          'component-hover': 'var(--figma-color-border-component-hover)',
          'component-strong': 'var(--figma-color-border-component-strong)',
          'danger': 'var(--figma-color-border-danger)',
          'danger-strong': 'var(--figma-color-border-danger-strong)',
          'success': 'var(--figma-color-border-success)',
          'success-strong': 'var(--figma-color-border-success-strong)',
          'warning': 'var(--figma-color-border-warning)',
          'warning-strong': 'var(--figma-color-border-warning-strong)',
          'disabled': 'var(--figma-color-border-disabled)',
          'disabled-strong': 'var(--figma-color-border-disabled-strong)',
          'selected': 'var(--figma-color-border-selected)',
          'selected-strong': 'var(--figma-color-border-selected-strong)',
          'onbrand': 'var(--figma-color-border-onbrand)',
          'onbrand-strong': 'var(--figma-color-border-onbrand-strong)',
          'oncomponent': 'var(--figma-color-border-oncomponent)',
          'oncomponent-strong': 'var(--figma-color-border-oncomponent-strong)',
          'ondanger': 'var(--figma-color-border-ondanger)',
          'ondanger-strong': 'var(--figma-color-border-ondanger-strong)',
          'onsuccess': 'var(--figma-color-border-onsuccess)',
          'onsuccess-strong': 'var(--figma-color-border-onsuccess-strong)',
          'onwarning': 'var(--figma-color-border-onwarning)',
          'onwarning-strong': 'var(--figma-color-border-onwarning-strong)',
          'onselected': 'var(--figma-color-border-onselected)',
          'onselected-strong': 'var(--figma-color-border-onselected-strong)',
        },
        
        // Icon colors
        'figma-icon': {
          DEFAULT: 'var(--figma-color-icon)',
          'hover': 'var(--figma-color-icon-hover)',
          'pressed': 'var(--figma-color-icon-pressed)',
          'secondary': 'var(--figma-color-icon-secondary)',
          'secondary-hover': 'var(--figma-color-icon-secondary-hover)',
          'tertiary': 'var(--figma-color-icon-tertiary)',
          'tertiary-hover': 'var(--figma-color-icon-tertiary-hover)',
          'brand': 'var(--figma-color-icon-brand)',
          'brand-pressed': 'var(--figma-color-icon-brand-pressed)',
          'brand-secondary': 'var(--figma-color-icon-brand-secondary)',
          'brand-tertiary': 'var(--figma-color-icon-brand-tertiary)',
          'component': 'var(--figma-color-icon-component)',
          'component-pressed': 'var(--figma-color-icon-component-pressed)',
          'component-secondary': 'var(--figma-color-icon-component-secondary)',
          'component-tertiary': 'var(--figma-color-icon-component-tertiary)',
          'danger': 'var(--figma-color-icon-danger)',
          'danger-hover': 'var(--figma-color-icon-danger-hover)',
          'danger-pressed': 'var(--figma-color-icon-danger-pressed)',
          'danger-secondary': 'var(--figma-color-icon-danger-secondary)',
          'danger-tertiary': 'var(--figma-color-icon-danger-tertiary)',
          'success': 'var(--figma-color-icon-success)',
          'success-pressed': 'var(--figma-color-icon-success-pressed)',
          'success-secondary': 'var(--figma-color-icon-success-secondary)',
          'success-tertiary': 'var(--figma-color-icon-success-tertiary)',
          'warning': 'var(--figma-color-icon-warning)',
          'warning-pressed': 'var(--figma-color-icon-warning-pressed)',
          'warning-secondary': 'var(--figma-color-icon-warning-secondary)',
          'warning-tertiary': 'var(--figma-color-icon-warning-tertiary)',
          'disabled': 'var(--figma-color-icon-disabled)',
          'onbrand': 'var(--figma-color-icon-onbrand)',
          'onbrand-secondary': 'var(--figma-color-icon-onbrand-secondary)',
          'onbrand-tertiary': 'var(--figma-color-icon-onbrand-tertiary)',
          'oncomponent': 'var(--figma-color-icon-oncomponent)',
          'oncomponent-secondary': 'var(--figma-color-icon-oncomponent-secondary)',
          'oncomponent-tertiary': 'var(--figma-color-icon-oncomponent-tertiary)',
          'ondanger': 'var(--figma-color-icon-ondanger)',
          'ondanger-secondary': 'var(--figma-color-icon-ondanger-secondary)',
          'ondanger-tertiary': 'var(--figma-color-icon-ondanger-tertiary)',
          'onsuccess': 'var(--figma-color-icon-onsuccess)',
          'onsuccess-secondary': 'var(--figma-color-icon-onsuccess-secondary)',
          'onsuccess-tertiary': 'var(--figma-color-icon-onsuccess-tertiary)',
          'onwarning': 'var(--figma-color-icon-onwarning)',
          'onwarning-secondary': 'var(--figma-color-icon-onwarning-secondary)',
          'onwarning-tertiary': 'var(--figma-color-icon-onwarning-tertiary)',
          'ondisabled': 'var(--figma-color-icon-ondisabled)',
          'oninverse': 'var(--figma-color-icon-oninverse)',
          'onselected': 'var(--figma-color-icon-onselected)',
          'onselected-secondary': 'var(--figma-color-icon-onselected-secondary)',
          'onselected-tertiary': 'var(--figma-color-icon-onselected-tertiary)',
          'onselected-strong': 'var(--figma-color-icon-onselected-strong)',
          'selected': 'var(--figma-color-icon-selected)',
          'selected-secondary': 'var(--figma-color-icon-selected-secondary)',
          'selected-tertiary': 'var(--figma-color-icon-selected-tertiary)',
        },
      },
      
      // Spacing
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '28': '112px',
        '32': '128px',
        '36': '144px',
        '40': '160px',
        '44': '176px',
        '48': '192px',
        '52': '208px',
        '56': '224px',
        '60': '240px',
        '64': '256px',
        '72': '288px',
        '80': '320px',
        '96': '384px',
      },
      
      // Border radius
      borderRadius: {
        'none': '0',
        'sm': '4px',
        'DEFAULT': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '20px',
        '3xl': '24px',
        'full': '9999px',
      },
      
      // Typography
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        display: ['Whyte', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
      },
      
      fontWeight: {
        normal: '450',
        medium: '500',
        semibold: '550',
        bold: '600',
      },
      
      fontSize: {
        // Figma UI3 type scale
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '450' }],
        'heading-1': ['24px', { lineHeight: '32px', letterSpacing: '-0.017em', fontWeight: '550' }],
        'heading-2': ['15px', { lineHeight: '25px', letterSpacing: '-0.0037em', fontWeight: '550' }],
        'heading-3': ['13px', { lineHeight: '22px', letterSpacing: '-0.0025em', fontWeight: '550' }],
        'body-large': ['13px', { lineHeight: '22px', letterSpacing: '-0.0025em', fontWeight: '450' }],
        'body-large-strong': ['13px', { lineHeight: '22px', letterSpacing: '-0.0025em', fontWeight: '550' }],
        'body': ['11px', { lineHeight: '16px', letterSpacing: '0.005em', fontWeight: '450' }],
        'body-strong': ['11px', { lineHeight: '16px', letterSpacing: '0.005em', fontWeight: '550' }],
        'body-small': ['9px', { lineHeight: '14px', letterSpacing: '0.005em', fontWeight: '450' }],
        'body-small-strong': ['9px', { lineHeight: '14px', letterSpacing: '0.005em', fontWeight: '550' }],
      },
      
      // Shadows
      boxShadow: {
        'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        'sm': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
        'DEFAULT': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'md': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'lg': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
        '2xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        'none': 'none',
        // Focus rings using Figma variables
        'focus': '0 0 0 2px var(--figma-color-border-selected)',
        'focus-inner': '0 0 0 1px var(--figma-color-border-selected) inset',
      },
      
      // Animation
      transitionDuration: {
        '0': '0ms',
        '75': '75ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '300': '300ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      
      // Z-index scale
      zIndex: {
        '0': '0',
        '10': '10',
        '20': '20',
        '30': '30',
        '40': '40',
        '50': '50',
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
        'dropdown': '1000',
        'sticky': '1020',
        'fixed': '1030',
        'modal-backdrop': '1040',
        'modal': '1050',
        'popover': '1060',
        'tooltip': '1070',
      },
    },
  },
  plugins: [],
}